import fs from 'node:fs/promises';
import path from 'node:path';
import { PARAMS_100 } from '../src/core/params';
import type { ParamDef } from '../src/core/params';

async function writeOutputs(outDir = path.join(process.cwd(), 'generated')) {
  await fs.mkdir(outDir, { recursive: true });

  const jsonPath = path.join(outDir, 'params-100.json');
  await fs.writeFile(jsonPath, JSON.stringify(PARAMS_100, null, 2), 'utf8');

  const tsPath = path.join(outDir, 'params-100.ts');
  const tsContent = `// Generated by generator/motion3d-2m.ts\nimport type { ParamDef } from '../src/core/params';\nexport const PARAMS_100: ParamDef[] = ${JSON.stringify(PARAMS_100, null, 2)};\nexport default PARAMS_100;\n`;
  await fs.writeFile(tsPath, tsContent, 'utf8');

  return { jsonPath, tsPath };
}

export async function generate(outDir?: string) {
  const res = await writeOutputs(outDir);
  return res;
}

if (require.main === module) {
  generate()
    .then(paths => {
      // eslint-disable-next-line no-console
      console.log('Generated PARAMS_100 files:', paths);
    })
    .catch(err => {
      // eslint-disable-next-line no-console
      console.error('Generation failed:', err);
      process.exit(1);
    });
}
