import fs from 'node:fs/promises';
import path from 'node:path';
import { ParamDef } from '../src/core/params';

const PARAMS_100: ParamDef[] = [
  // minimal duplication: import from core/params would be ideal, but keep a local reference for generator independence
];

async function writeOutputs(outDir = path.join(process.cwd(), 'generated')) {
  await fs.mkdir(outDir, { recursive: true });
  const jsonPath = path.join(outDir, 'params-100.json');
  await fs.writeFile(jsonPath, JSON.stringify(PARAMS_100, null, 2), 'utf8');
  const tsPath = path.join(outDir, 'params-100.ts');
  const tsContent = `// Generated by generator/motion3d-2m.ts\nexport const PARAMS_100 = ${JSON.stringify(PARAMS_100, null, 2)} as const;\nexport default PARAMS_100;\n`;
  await fs.writeFile(tsPath, tsContent, 'utf8');
  return { jsonPath, tsPath };
}

export async function generate(outDir?: string) {
  const res = await writeOutputs(outDir);
  return res;
}

if (require.main === module) {
  generate().then(p => console.log('Generated', p)).catch(e => { console.error(e); process.exit(1); });
}
